version: 2
updates:
    # Python dependencies via rye
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "monday"
      open-pull-requests-limit: 5
      reviewers:
        - "kimata"
      assignees:
        - "kimata"
      commit-message:
        prefix: "deps"
        include: "scope"

    # React frontend dependencies
    - package-ecosystem: "npm"
      directory: "/react"
      schedule:
        interval: "weekly"
        day: "monday"
      open-pull-requests-limit: 5
      reviewers:
        - "kimata"
      assignees:
        - "kimata"
      commit-message:
        prefix: "deps"
        include: "scope"

    # Alternative React app dependencies
    - package-ecosystem: "npm"
      directory: "/myappname"
      schedule:
        interval: "weekly"
        day: "monday"
      open-pull-requests-limit: 3
      reviewers:
        - "kimata"
      assignees:
        - "kimata"
      commit-message:
        prefix: "deps"
        include: "scope"

    # GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "monthly"
      open-pull-requests-limit: 3
      reviewers:
        - "kimata"
      assignees:
        - "kimata"
      commit-message:
        prefix: "ci"
        include: "scope"
