influxdb:
  url: http://tanzania.green-rabbit.net:8086
  token: fffjkjkgfklhjglkjiojtroijojhkljhklghklfjklhhlnklhnklfgnhklgnhgfdlhfgnhlkngdfnfnhgdkfnh==
  org: home
  bucket: sensor

sensor:
  temperature:
    - name: 外気温
      measure: sensor.esp32
      hostname: ESP32-outdoor-1
  power:
    - name: リビングエアコン
      measure: hems.sharp
      hostname: リビングエアコン
    - name: 書斎エアコン
      measure: fplug
      hostname: 書斎エアコン
    - name: 和室エアコン
      measure: fplug
      hostname: 和室エアコン

valve:
  pin_no: 17 # BCM で指定

mail:
  user: XXXX@gmail.com
  pass: XXXXXX
  to: XXXX@gmail.com
  from: XXXX@gmail.com
