version: '2.4'
services:
  unit_cooler:
    image: registry.green-rabbit.net:5000/kimata/outdoor_unit_cooler:latest
    environment:
      - HEMS_SERVER_HOST=192.168.0.20
    volumes:
      - type: bind
        source: ../hems_config/unit_cooler.yaml
        target: config.yaml
    devices:
    - /dev/gpiomem
    - /dev/spidev0.0
