kind: Namespace
apiVersion: v1
metadata:
    name: hems
    labels:
        name: hems
---
kind: Service
apiVersion: v1
metadata:
    name: unit-cooler-controller
    namespace: hems
    annotations:
        metallb.universe.tf/address-pool: default
        external-dns.alpha.kubernetes.io/hostname: unit-cooler-controller.kubernetes.green-rabbit.net
spec:
    selector:
        app: unit-cooler-controller
    ports:
        - port: 2222
          targetPort: 2222
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: unit-cooler-controller
    namespace: hems
    labels:
        app: unit-cooler-controller
spec:
    replicas: 1
    selector:
        matchLabels:
            app: unit-cooler-controller
    template:
        metadata:
            labels:
                app: unit-cooler-controller
        spec:
            containers:
                - name: unit-cooler-controller
                  image: registry.green-rabbit.net:5000/kimata/unit-cooler:latest
                  imagePullPolicy: Always
                  command: ["./src/controller.py"]
                  ports:
                      - containerPort: 2222
                  resources:
                      requests:
                          memory: 256Mi
                      limits:
                          memory: 512Mi
                  livenessProbe:
                      exec:
                          command:
                              - /opt/unit_cooler/src/healthz.py
                              - "-m"
                              - CTRL
                      initialDelaySeconds: 120
                      periodSeconds: 120
                      timeoutSeconds: 30
                      successThreshold: 1
                      failureThreshold: 3
            dnsPolicy: Default
            nodeSelector:
                kubernetes.io/hostname: hems
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: unit-cooler-actuator
    namespace: hems
    labels:
        app: unit-cooler-actuator
spec:
    replicas: 1
    selector:
        matchLabels:
            app: unit-cooler-actuator
    template:
        metadata:
            labels:
                app: unit-cooler-actuator
        spec:
            volumes:
                - name: dev-gpio
                  hostPath:
                      path: /dev/gpiomem
                - name: dev-spidev
                  hostPath:
                      path: /dev/spidev0.0
                - name: dev-tty
                  hostPath:
                      path: /dev/ttyAMA0
            containers:
                - name: unit-cooler-actuator
                  image: registry.green-rabbit.net:5000/kimata/unit-cooler:latest
                  imagePullPolicy: Always
                  command: ["./src/actuator.py"]
                  env:
                      - name: HEMS_SERVER_HOST
                        value: unit-cooler-controller.hems.svc.cluster.local
                      - name: NODE_HOSTNAME
                        value: rasp-cooler-1
                  volumeMounts:
                      - mountPath: /dev/gpiomem
                        name: dev-gpio
                      - mountPath: /dev/spidev0.0
                        name: dev-spidev
                      - mountPath: /dev/ttyAMA0
                        name: dev-tty
                  securityContext:
                      privileged: true
                  resources:
                      requests:
                          memory: 256Mi
                      limits:
                          memory: 512Mi
                  livenessProbe:
                      exec:
                          command:
                              - /opt/unit_cooler/src/healthz.py
                              - "-m"
                              - ACT
                      initialDelaySeconds: 120
                      periodSeconds: 120
                      timeoutSeconds: 30
                      successThreshold: 1
                      failureThreshold: 3
            dnsPolicy: ClusterFirst
            nodeSelector:
                kubernetes.io/hostname: rasp-cooler-1
---
kind: Service
apiVersion: v1
metadata:
    name: unit-cooler-webui
    namespace: hems
    annotations:
        metallb.universe.tf/address-pool: default
        external-dns.alpha.kubernetes.io/hostname: unit_cooler.kubernetes.green-rabbit.net
spec:
    selector:
        app: unit-cooler-webui
    ports:
        - port: 5000
          targetPort: 5000
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: unit-cooler-webui
    namespace: hems
    labels:
        app: unit-cooler-webui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: unit-cooler-webui
    template:
        metadata:
            labels:
                app: unit-cooler-webui
        spec:
            containers:
                - name: unit-cooler-controller
                  image: registry.green-rabbit.net:5000/kimata/unit-cooler:latest
                  imagePullPolicy: Always
                  command: ["./src/webui.py"]
                  ports:
                      - containerPort: 5000
                  env:
                      - name: HEMS_SERVER_HOST
                        value: unit-cooler-controller.hems.svc.cluster.local
                  resources:
                      requests:
                          memory: 128Mi
                      limits:
                          memory: 256Mi
                  livenessProbe:
                      exec:
                          command:
                              - /opt/unit_cooler/src/healthz.py
                              - "-m"
                              - WEB
                      initialDelaySeconds: 120
                      periodSeconds: 120
                      timeoutSeconds: 30
                      successThreshold: 1
                      failureThreshold: 3
            dnsPolicy: ClusterFirst
            nodeSelector:
                kubernetes.io/hostname: worker
