name: Lint and Type Check
on:
    push:
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install Rye
              run: |
                curl -sSf https://rye.astral.sh/get | RYE_NO_AUTO_INSTALL=1 RYE_INSTALL_OPTION="--yes" bash
                echo "$HOME/.rye/shims" >> $GITHUB_PATH

            - name: Cache python modules
              uses: actions/cache@v4
              with:
                path: ~/.cache/rye
                key: ${{ runner.os }}-rye-lint-${{ hashFiles('pyproject.toml', 'requirements*.lock') }}
                restore-keys: |
                    ${{ runner.os }}-rye-lint-

            - name: Install Dependencies
              run: rye sync

            - name: Run pre-commit hooks
              run: rye run pre-commit run --all-files
              continue-on-error: true

            - name: Run ruff linting
              run: rye run ruff check .

            - name: Run ruff formatting check
              run: rye run ruff format --check .

    frontend-lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
                cache-dependency-path: 'react/package-lock.json'

            - name: Install Dependencies
              run: npm ci
              working-directory: ./react

            - name: Run ESLint
              run: npm run lint
              working-directory: ./react
              continue-on-error: true

            - name: Check TypeScript types
              run: npx tsc --noEmit
              working-directory: ./react
              continue-on-error: true
